### ISSUE TITLE
Documentation Updates

### ISSUE THREAD

**Issue by Mainchains** [hyperledger/sawtooth-docs#10]
Hello hyperledger,

I was recently running through the tutorial posted on the sawtooth docs when I realized that something was wrong. I will try to be as verbose as I can be. I should note that maybe 10 days ago, I had run through the entire tutorial with no problems. Things that particularly stand out to me, I place in bold.

Version Information:
I have run the tutorial to the button, my vagrant version is 1.8.4 and vbox is 5.0.26. I am on OSX El Cap and have forked the most recent version of sawtooth from both hyperledger and intelledger. I have not touched any files except for what is mentioned explicitly below (accompanied with the command).

Expected Results:
A dummy validator starts up and listens for transactions.

Actual Results:
The validator does not start, it cannot find an endpoint or keys. Details below.

Explanation: 

I encounter the following errors when doing a run through the tutorial:
Upon using vagrant ssh into my fresh box, I execute the $`python setup.py build` command. This completes with the following compiler warnings when building source from the journal/consensus/poet/poet_enclave_simulator/* directory:

cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]

After The build, the tutorial directs us to start up a dummy validator using the following command from the /project/sawtooth-validator/ directory:

./bin/txnvalidator -v --http 8800 --config /project/sawtooth-docs/source/tutorial/txnvalidator.js

1. The protocol http is no longer an argument, 
**txnvalidator: error: unrecognized arguments: --http 8800**

2. I remove the unrecognized command and execute, resulting in the following stack trace. Notice that the key base000.wif has not yet been generated, and the there is a mission endpoint for the gossip protocol. The keys are strange, because I thought that they were provided, maybe the file got removed? I am not sure how to provide the endpoint in configuration. I tried some --listen args to no avail.

vagrant@vagrant-ubuntu-trusty-64:/project/sawtooth-validator$ **./bin/txnvalidator -v --config /project/sawtooth-docs/source/tutorial/txnvalidator.js** 
[16:05:58 INFO    validator_cli] validator started with arguments: ['./bin/txnvalidator', '-v', '--config', '/project/sawtooth-docs/source/tutorial/txnvalidator.js']
[16:05:58 WARNING validator_cli] **unable to find locate key file /project/sawtooth-validator//keys/base000.wif**
[16:06:00 WARNING validator_cli] validator pid is 9959
Traceback (most recent call last):
  File "./bin/txnvalidator", line 21, in <module>
    main_wrapper()
  File "/project/sawtooth-validator/txnmain/validator_cli.py", line 406, in main_wrapper
    main(sys.argv[1:])
  File "/project/sawtooth-validator/txnmain/validator_cli.py", line 397, in main
    local_main(cfg, windows_service)
  File "/project/sawtooth-validator/txnmain/validator_cli.py", line 69, in local_main
    windows_service=windows_service)
  File "/project/sawtooth-validator/txnserver/lottery_validator.py", line 28, in __init__
    super(LotteryValidator, self).__init__(config, windows_service)
  File "/project/sawtooth-validator/txnserver/validator.py", line 59, in __init__
    'gossip listen address is 0.0.0.0, but endpoint host '
**Exception: gossip listen address is 0.0.0.0, but endpoint host missing from configuration**

3. I generated the keys base000.wif and base000.addr, and changed the appropriate 
vagrant@vagrant-ubuntu-trusty-64:/project/sawtooth-validator$ ./bin/txnkeygen --keydir keys base000
writing file: keys/base000.wif
writing file: keys/base000.addr

and then run the command again, it results in the same stack trace ending in **Exception: gossip listen address is 0.0.0.0, but endpoint host missing from configuration**

In general, I believe the main issue is the change in command line arguments for the txnvalidator. It seems that the argument --http 8800 was changed/integrated into --listen or moved to a config file.

Thanks for your time and happy coding :)

**Comment by boydjohnson** [comment]
Hi, right now the docs, which contain a txnvalidator.js file, aren't up to date with recent networking changes in sawtooth-validator. I recommend if you are going through the tutorial use sawtooth-validator/etc/txnvalidator.js, and add mktplace.transactions.market_place.MarketPlace to TransactionFamilies.

Please reach out again if there is a mistake in the docs. We will get on them.

**Comment by feihujiang** [comment]
@Mainchains you could start the txnvalidato by using the following commands:
~~~
 $ cd /project/sawtooth-validator
 $ ./bin/txnvalidator -v --config ./etc/txnvalidator.js --genesis
~~~

```unable to find locate key file /project/sawtooth-validator//keys/base000.wif```: Yes, the file isn't provided. and the validator generates a random signing key.
 
If you want to practise the mktplace example,  you should edit ./etc/txnvalidator.js  and add "mktplace.transactions.market_place" to the list of transaction families:
~~~
"TransactionFamilies" : [
    "ledger.transaction.integer_key",
    "mktplace.transactions.market_place"
],
~~~
Hope these lines helpful for you.

**Comment by boydjohnson** [comment]
We now have an external Jira and this issue is included in a [Jira ticket.](https://jira.hyperledger.org/projects/STL/issues/STL-1?filter=allopenissues)

**Comment by jkolluru** [comment]
Boydjohnson:
Not sure if I can continue on the same question. But I get the following error:

vagrant@vagrant-ubuntu-trusty-64:/project/sawtooth-validator$ ./bin/txnvalidator -v --config ./etc/
txnvalidator.js --genesis
: No such file or directory

Would you be able to throw some light on this

**Comment by feihujiang** [comment]
@jkolluru  The '''./etc/txnvalidator.js''' file is missing, you could copy '''./etc/txnvalidator.js.example''' file to a new file '''./etc/txnvalidator.js''' in the same directory, then using it.

**Comment by jkolluru** [comment]
I was having issues with the files that I got from git. As I am using Windows 10, I needed to setup the git config paramater:

git config --global core.autocrlf false

This solved most of the issues and things worked.
Of course, I needed to use the new file '''./etc/txnvalidator.js'''

**Comment by Mainchains** [comment]
Thank you everyone!
